@startuml matching-disconnect

participant "user1:Frontend" as user1
participant QuestionService
database mongodb

activate user1
user1 -> QuestionService: searchQuestionByDifficulty(difficulty, username, collabName)
activate QuestionService


QuestionService -> mongodb: searchQuestionByDifficulty(difficulty, username, collabName)

note over QuestionService
    Returns the first question 
    that has not been attempted
    by both users in the DB.
end note

mongodb --> QuestionService: question

QuestionService -> user1: question

deactivate QuestionService


note over user1
    After a period of time, 
    user exits from the room.
end note

user1 -> QuestionService: attemptQuestion(title,username)
activate QuestionService
deactivate QuestionService
user1 -> QuestionService: attemptQuestion(title,collabName)
activate QuestionService
deactivate QuestionService


@enduml

